### ISSUE TITLE
Graph Diagrams

### ISSUE THREAD

**Issue by petarmhg** [rsokl/MyGrad#25]
Add a `construct_graph` function to Tensors that creates a visual graph of a network.

Example:

```python
"
 /‾‾‾\
| out |
 \___/
   Λ
   |
   |
   |
 |‾‾‾|
 | + |
 |___|
   Λ
   |
   |‾‾‾‾‾‾‾|
   |       |
   |       |
 /‾‾‾\   /‾‾‾\
|  Z  | |  K  |
 \___/   \___/
           Λ
           |
           |
           |
         |‾‾‾|
         | * |
         |___|
           Λ
           |
      |‾‾‾‾‾‾‾‾‾|
      |         |
      |         |
    /‾‾‾\    /‾‾‾\
   |  X  |  |  Y  |
    \___/    \___/
"
```

**Comment by Anonymission** [comment]
I currently have MyGrad able to produce graphs like this (colors/node shapes can be easily changed) using pydot:

![network_graph](https://user-images.githubusercontent.com/16225848/41504449-39ca6712-71bd-11e8-8829-0a79db8ed3c9.png)

However, because of the possibility that two tensors will have the same data, I need to use `id()` to get the unique memory addresses of the tensors which I then include in the node names. Similarly, I use `__repr__` to get the operator function names and addresses. This has two big drawbacks: graph building can only be done with CPython and the final graph has those ugly (and potentially confusing) sequences underneath the tensors/operators though.

Any ideas for other ways to uniquely identify similar tensors and operators?

**Comment by davidmascharka** [comment]
Nice! Do you have a branch with code somewhere we can take a look at? I'm not sure I quite understand the issue you're having.

**Comment by Anonymission** [comment]
PR #60 has the code.

The first reason I need to use unique identifiers is because I use a dictionary to store all the operations and there creators (which is updated whenever a new tensor is created). This makes it easier to build the graph when the build_graph method is called on a tensor. In the example above, `_graph_dict` would look like: 

```python
{'[1 2]\n4475662064': None,
 '[1 2]\n4475662120': None,
 '[14 24]\n4471837472': <mygrad.math.arithmetic.ops.Multiply at 0x10ac4aba8>,
 '[14 24]\n4475660832': <mygrad.math.arithmetic.ops.Subtract at 0x10ac52b70>,
 '[15 26]\n4475660776': <mygrad.math.arithmetic.ops.Add at 0x10ac52c18>,
 '[2 3]\n4475662176': None,
 '[7 8]\n4475662288': None}
```

The network this represents is the following:
```python
a = Tensor(np.array([1, 2]))
b = Tensor(np.array([2, 3]))
c = Tensor(np.array([7, 8]))
e = Tensor(np.array([1, 2]))
d = a + b * c - e
```

Since two tensors may have the same data (such as the first two in the above dictionary), I use `id()` to get their memory addresses to make unique keys to the dictionary.

While the dictionary can easily be adapted, the bigger problem is that graphviz requires all unique nodes to have unique names. This means if I were to remove the `id()` numbers, graphviz would build a graph where `a` and `e` are the same node, instead of two separate nodes.

**Comment by davidmascharka** [comment]
One thing you can do is pass in a `label` argument to the `Node` objects. Names do have to be unique but labels certainly don't:

``` python
import pydot
graph = pydot.Dot(graph_type='digraph')

node1 = pydot.Node('test1')
node2 = pydot.Node('test2')
node3 = pydot.Node('test3', label='test1')

for node in (node1, node2, node3):
    graph.add_node(node)
graph.add_edge(pydot.Edge('test1', 'test2'))
graph.write_png('test.png')
```
![test](https://user-images.githubusercontent.com/5611862/41730492-291bf1b8-7539-11e8-8002-7d739dc9f300.png)

In some cases it can be useful to put in the tensor data as the node label like you're doing now but that definitely won't be ideal for, say, visualizing the computational graph of a neural network. If there was an option to plot either the tensor data or the variable name that would be super convenient. Just a thought

**Comment by Anonymission** [comment]
That's perfect. Just pushed an update that adds labels to Nodes. It also now allows the user to either specify a name for specific Nodes or to pass in `locals()` and use the variable names already assigned when constructing the network.

Example:
```python
import numpy as np
from mygrad.tensor_base import Tensor
from mygrad.nnet.layers import dense
from mygrad import logaddexp
from mygrad.computational_graph import build_graph

a = Tensor(np.array([[1, 2], [3, 4]]))
b = Tensor(np.array([[2, 3], [9, 7]]))
c = Tensor(np.array([[7, 8], [12, 34]]))
d = Tensor(np.array([[1, 2], [3, 4]]))

e = a + b
f = dense(c, e)
g = logaddexp(f, d)
h = d + g

build_graph(h, names=locals())
```

Will result in:

![computational_graph](https://user-images.githubusercontent.com/16225848/41859384-1356d38c-786a-11e8-8625-35958f57d5ad.png)

**Comment by Anonymission** [comment]
Do you think it would also be worthwhile to include the dimensions of each Tensor object, especially when names are specified for the Nodes? It might make it a little easier to understand and follow.

**Comment by rsokl** [comment]
Wow this is looking great! I do think that tensor shapes could be useful metadata to have. Other potential ideas would be to include the min/max/mean of the tensors to summarize their contents. Just a thought.

**Comment by davidmascharka** [comment]
Awesome! I agree; shapes are super useful to have. Thinking back to my Theano days, things like data types can also be useful:

![graph](https://user-images.githubusercontent.com/5611862/41868108-1c877cea-7883-11e8-8069-d73fda5edc60.png)

**Comment by rsokl** [comment]
@Anonymission have you seen [toytree](http://toytree.readthedocs.io/en/latest/tutorial/)? It looks like a really sleek tree-drawing interface. What is especially nice is that it is designed to render within jupyter notebooks, which is really the ideal setup for us.

**Comment by Anonymission** [comment]
@rsokl Here's a rough sample I set up using toytree:

```python
a = Tensor(np.array([[1, 2], [3, 4]]))
b = Tensor(np.array([[2, 3], [9, 7]]))
c = Tensor(np.array([[7, 8], [12, 34]]))
d = Tensor(np.array([[1, 2], [3, 4]]))

e = a + b
f = dense(c, e)
g = logaddexp(f, d)
h = d + g

build_graph(h, names=locals())
```

![screen shot 2018-06-29 at 11 52 16 am](https://user-images.githubusercontent.com/16225848/42102104-f6cec810-7b92-11e8-8cdd-64021b23be27.png)


Note that the 'i12', 'i11', etc. are operations and outputs (I am still trying to figure out how to get those to display useful labels).

I don't believe there is a way for the same tensor to have multiple branch coming from it, but for simpler graphs it could be nice to have this quickly preview in a jupyter notebook

**Comment by rsokl** [comment]
@Anonymission this is looking great to me. I recall seeing that labels can be specified for the nodes. Having a sleek, in-notebook view of the computational graph would be tremendous :)

**Comment by Anonymission** [comment]
@rsokl it looks like graphviz has its own [python interface](https://graphviz.readthedocs.io/en/stable/manual.html#jupyter-notebooks) that supports in-notebook rendering of graphs. Given the problems that toytree has had with labelling, I think that using graphviz here would be best.
