### ISSUE TITLE
The GRU has dtype compatibility issues

### ISSUE THREAD

**Issue by rsokl** [rsokl/MyGrad#261]
The GRU dies when dealing with mixes of float-32 and float64 data/parameters

**Comment by petarmhg** [comment]
The dtype of the data shouldn't break the GRU - the data isn't directly used in any operation inside any of the numba jitted functions. The issue is related to the dtype of the parameters and the line

```python
out = np.zeros((T + 1, N, D))
```

as `np.zeros` will by default create an array of `float64`s. Casting all the parameters to the biggest dtype (and ensuring `out` is also made to be this dtype) should resolve the bug.
