### ISSUE TITLE
argmax/argmin

### ISSUE THREAD

**Issue by davidmascharka** [rsokl/MyGrad#58]
They should exist as non-differentiable functions in Tensor. These should merely be wrappers on the numpy functions so that they can also accept tensors. These functions should return numpy arrays.

**Comment by alexding123** [comment]
Would like to handle this. Not a contributor so can't self-assign. Will pull-request when done.

**Comment by davidmascharka** [comment]
Awesome! I'm not sure how to best handle assignment since this isn't an org so for now I'll make a new "in-progress" tag.

@rsokl can chime in with how he wants the operations separated out (i.e. in a `nondifferentiable` package or subsumed under the current `math` package).

**Comment by rsokl** [comment]
@alexding123 I think that these should go under `mygrad.math.nondifferentiable` (of course they'll be available at top-level, so people wont have to know how to spell that). These will exist as functions, which we can then simply set as methods

We'll want to forego calling `_op` as the output of argmax/argmin will be numpy-arrays and not tensors, and there is no need to hook into any computational graph at all. Thus you will simply want to implement these as functions that normalize the input to numpy's argmax/argmin functions so that mygrad-tensors can be accepted in addition to other array_like objects.

Once you write those function, we can still conform to the pattern of making these functions as methods of `Tensor` in addition to being standalone functions, as seen [here](https://github.com/rsokl/MyGrad/blob/d6dff60f598a3c28467832e60043187af4c7db3c/mygrad/__init__.py#L19). This will make maintainability and testability simple, as you were hoping for.

Let me know if this makes sense.
